name: ng_bootstrap
version: 0.7.1
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular: ^4.0.0-alpha+2
  browser: ^0.10.0
  node_shims: ^0.1.3
  intl: ^0.15.0
  dart_to_js_script_rewriter: ^1.0.1
  markdown: ^0.11.3
  sass: ^1.0.0-alpha.9
  bootstrap_sass: ^4.0.0-alpha.5+1
#  bootstrap_sass:
#    path: ../bootstrap_sass
  stream_transformers: ^0.3.0+3
#  stream_transformers:
#    path: ../stream_transformers
  font_awesome: ^4.6.3
  dev_string_converter: ^0.1.0
dev_dependencies:
  build_runner: ^0.3.4
  sass_builder: ^0.1.1
#  sass_builder:
#    path: ../sass_builder
transformers:
- angular
- dart_to_js_script_rewriter
- $dart2js:
    $include: web/index.dart
